name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      - name: zainstaluj paczki
        run: npm install
      - name: uruchom testy
        run: npx newman run './postman/collections/Trello Copy.json'


